name: LocalFlow
options:
  bundleIdPrefix: com.localflow
  deploymentTarget:
    macOS: "26.0.99"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  LocalFlowApp:
    type: application
    platform: macOS
    deploymentTarget: "26.0.99"
    sources:
      - path: LocalFlowApp
    resources:
      - path: LocalFlowApp/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.localflow.app
      PRODUCT_NAME: LocalFlow
      INFOPLIST_FILE: LocalFlowApp/Info.plist
      CODE_SIGN_ENTITLEMENTS: LocalFlowApp.entitlements
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "26.0.99"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
    info:
      path: LocalFlowApp/Info.plist
      properties:
        LSUIElement: true
        NSHighResolutionCapable: true

